### ISSUE TITLE
Development Fails

### ISSUE THREAD

**Issue by RaiMX** [GeoNode/geonode-mapstore-client#1384]
When starting this project from scratch, during `npm install` it shows tons of deprecated packages. Then after `npm start` it shows the error below.
I use 
```
node v12.18.4
npm 6.14.6
```

What did I miss?

ERROR duting `npm start`

```
(geonode)  raimx@pop-os  ~/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client   master ±  npm run start

> geonode-mapstore-client@4.0.0 start /home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client
> mapstore-project start

 
 -------------------------------------------------------------------------------
   start dev
 -------------------------------------------------------------------------------
 
 

Build Entries:
- Apps: {
    "js/gn-catalogue": "./js/apps/gn-catalogue.js",
    "js/gn-components": "./js/apps/gn-components.js",
    "js/gn-dashboard": "./js/apps/gn-dashboard.js",
    "js/gn-document": "./js/apps/gn-document.js",
    "js/gn-geostory": "./js/apps/gn-geostory.js",
    "js/gn-map": "./js/apps/gn-map.js"
}
- HTML: {}
- Themes: {
    "themes/geonode": "./themes/geonode/theme.less"
}

9% setup compilation LoaderOptionsPlugin[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/MapStore2/node_modules/webpack/lib/NormalModule.js:171:10)
    at /home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/MapStore2/node_modules/webpack/lib/LoaderOptionsPlugin.js:43:17
    at Hook.eval [as call] (eval at create (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:287:1)
    at Hook.CALL_DELEGATE [as _call] (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Compiler.js:943:26)
    at /home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Compiler.js:984:29
    at Hook.eval [as callAsync] (eval at create (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Compiler.js:979:28)
    at /home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Watching.js:112:19
    at Hook.eval [as callAsync] (eval at create (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at run (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Watching.js:66:33)
    at Watching._go (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Watching.js:123:4)
    at /home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Watching.js:57:9
    at Compiler.readRecords (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Compiler.js:821:11)
    at new Watching (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Watching.js:54:17)
    at Compiler.watch (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack/lib/Compiler.js:362:19)
    at wdm (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-dev-middleware/index.js:41:33)
    at Server.setupDevMiddleware (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-dev-server/lib/Server.js:207:23)
    at new Server (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-dev-server/lib/Server.js:118:10)
    at Command.<anonymous> (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/@webpack-cli/serve/lib/index.js:254:34)
child_process.js:669
    throw err;
    ^

Error: Command failed: /home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/.bin/webpack serve --progress --color --port 8081 --hot --inline --config /home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/@mapstore/project/types/standard/config/webpack.config.js
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.<anonymous> (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/@mapstore/project/scripts/start.js:32:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 72187,
  stdout: null,
  stderr: null
}
child_process.js:669
    throw err;
    ^

Error: Command failed: node /home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/@mapstore/project/scripts/start.js --type=standard
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.<anonymous> (/home/raimx/DEV/kaznedra/geonode-mapstore-client/geonode_mapstore_client/client/node_modules/@mapstore/project/bin/mapstore-project.js:28:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 72179,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geonode-mapstore-client@4.0.0 start: `mapstore-project start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geonode-mapstore-client@4.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/raimx/.npm/_logs/2023-01-22T19_38_38_285Z-debug.log

```

**Comment by subramani-r-0595** [comment]
facing same issue. Can anyone please help?

**Comment by fedesanchez** [comment]
same problem here
