### ISSUE TITLE
Unable to load '@webpack-cli/serve' when running npm start with 3.2.1 tag

### ISSUE THREAD

**Issue by MoRadwan74** [GeoNode/geonode-mapstore-client#566]
I'm trying to run [geonode-mapstore-client@3.2.1](https://github.com/GeoNode/geonode-mapstore-client/releases/tag/3.2.1) release for development with NodeJS v12.18.4 and NPM 6.14.6.

When I run `npm start` this error related to webpack appears:
```bash
> geonode-mapstore-client@3.2.1 start /home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client
> mapstore-project start geonode

 
 -------------------------------------------------------------------------------
   start dev
 -------------------------------------------------------------------------------
 
 
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/lib/webpack-cli.js:108:21)
    at ServeCommand.apply (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/@webpack-cli/serve/lib/index.js:41:19)
    at loadCommandByName (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/lib/webpack-cli.js:626:35)
    at Command.<anonymous> (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/lib/webpack-cli.js:1091:23)
    at Command.listener [as _actionHandler] (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/node_modules/commander/index.js:1503:14)
    at Command.parse (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/node_modules/commander/index.js:1292:10)
    at Command.parseAsync (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/node_modules/commander/index.js:1318:10)
    at WebpackCLI.run (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/lib/webpack-cli.js:1123:28)
    at runCLI (/home/radwan/work/MapSaudi/mapsaudi-mapstore-client/geonode_mapstore_client/client/node_modules/webpack-cli/lib/bootstrap.js:11:19)
child_process.js:679
    throw err;
```

I tried different versions of NodeJS with nvm like v10.24.1, v14.17.0 and v16.13.0 with the same error.

Any thoughts?

**Comment by allyoucanmap** [comment]
Hi @MoRadwan74 ,

could you try to add this version of `webpack-cli` to the devDependencies of the 
`geonode-mapstore-client/geonode_mapstore_client/client/package.json` file and run `npm install` again to see if this solves the issue?

`"webpack-cli": "4.9.0",`

**Comment by MoRadwan74** [comment]
It works finally!! Thanks @allyoucanmap 

Is it related to the webpack regression issue reported [here](https://github.com/webpack/webpack-cli/issues/2990#issuecomment-937704258)?

**Comment by allyoucanmap** [comment]
@MoRadwan74 yes probably that's the reason

**Comment by MoRadwan74** [comment]
Okay closing this.

Thanks again @allyoucanmap.
